### ISSUE TITLE
Today (10/10) the auto check-in failed with the message: 活动已结束 (-500012)

### ISSUE THREAD

**Issue by andreofgyn** [Areha11Fz/HoYoLAB-Auto-Check-In#3]
Even after I updated the ltoken_v2 on the script the same message (活动已结束 / "event is over") appeared.

Manual check-in is ok.

**Comment by Areha11Fz** [comment]
Fixed now, you can check the latest commit.

**Comment by andreofgyn** [comment]
Perfect, thanks!
