### ISSUE TITLE
hsr check in not working

### ISSUE THREAD

**Issue by Keilo104** [Areha11Fz/HoYoLAB-Auto-Check-In#4]
same issue zzz was having earlier, i managed to fix it by doing some dumb stuff

        const httpResponses = UrlFetchApp.fetchAll(urls.map((url) => {
          const temp_options = JSON.parse(JSON.stringify(options));

          if (url.localeCompare(urlDict.ZZZ) == 0) temp_options["headers"]["x-rpc-signgame"] = "zzz";
          else if (url.localeCompare(urlDict.Star_Rail) == 0) temp_options["headers"]["x-rpc-signgame"] = "hsr";

          return { url, ...temp_options }
        }));

probably not the best way to do it, but it do be working now

**Comment by PhantomEnderium** [comment]
Wanted to add to this, the old version of the code before the ZZZ bugfix has starrail working fine, something in the updated code must be screwing with it. I'm not well versed in this type of code yet so I can't really help but wanted to point that out.

temp fix here does work though, thank you!!

**Comment by ankarakata** [comment]
> same issue zzz was having earlier, i managed to fix it by doing some dumb stuff
> 
> ```
>     const httpResponses = UrlFetchApp.fetchAll(urls.map((url) => {
>       const temp_options = JSON.parse(JSON.stringify(options));
> 
>       if (url.localeCompare(urlDict.ZZZ) == 0) temp_options["headers"]["x-rpc-signgame"] = "zzz";
>       else if (url.localeCompare(urlDict.Star_Rail) == 0) temp_options["headers"]["x-rpc-signgame"] = "hsr";
> 
>       return { url, ...temp_options }
>     }));
> ```
> 
> probably not the best way to do it, but it do be working now

what code/line should i replace with this fix?

**Comment by Keilo104** [comment]
@ankarakata replace the one line that starts with

`const httpResponses = UrlFetchApp...`

**Comment by w3djyt** [comment]
I'm getting "活动已结束 (-500012)" for one account but "操作频繁，请稍后再试" for the other... both HSR. 

Can confirm the above code fixed the problem for me. Thanks, @Keilo104

**Comment by Areha11Fz** [comment]
added fix, thanks for the info!
