### ISSUE TITLE
Not working on ZZZ since 10/10

### ISSUE THREAD

**Issue by Graylies047** [Areha11Fz/HoYoLAB-Auto-Check-In#5]
![Captura de tela 2024-10-20 204511](https://github.com/user-attachments/assets/8e3a02ed-ed5f-47f2-8af9-5e184535b335)
![Captura de tela 2024-10-20 204519](https://github.com/user-attachments/assets/957067b0-cdc7-43c1-86bd-bee0a1b80ea1)

**Comment by Areha11Fz** [comment]
Use the latest script, its updated
